name: voc_amp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # Connectivity
  connectivity: ^0.4.6+1
  dio_http_cache: ^0.2.5
  dio: ^3.0.5
  #Utils
  dartz: ^0.8.9
  json_annotation: ^3.0.0
  provider: ^3.2.0
  rxdart: ^0.23.1
  google_fonts: ^0.2.0
  uuid: ^2.0.4
  color: ^2.1.1
  color_thief_flutter: ^1.0.0
  # Widgets
  cached_network_image: ^2.0.0-rc
  auto_size_text: ^2.1.0
  fluttertoast: ^3.1.3
  # Audio
  audio_service: ^0.6.1
  youtube_explode_dart:
    git:
      url: https://github.com/BeMacized/youtube_explode_dart.git
      ref: d4302f689c1c3adcc8905600ff1f4ec23c49eefe
  just_audio: 0.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
