name: voc_amp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # Connectivity
  connectivity: ^0.4.6+1
  dio_http_cache: ^0.2.5
  dio: ^3.0.5
  #Utils
  dartz: ^0.8.9
  json_annotation: ^3.0.0
  provider: ^3.2.0
  rxdart: ^0.23.1
  google_fonts: ^0.2.0
  uuid: ^2.0.4
  color: ^2.1.1
  color_thief_flutter: ^1.0.0
  # Widgets
  cached_network_image: ^2.0.0-rc
  auto_size_text: ^2.1.0
  fluttertoast: ^3.1.3
  # Audio
  audio_service: ^0.5.6
  youtube_extractor:
    git:
      url: https://github.com/BeMacized/youtube-extractor.git
      ref: 5369df4414a2fe5b9d168c0f147f66aa85f1ff81
  just_audio: #^0.0.3
    git:
      url: https://github.com/BeMacized/just_audio.git
      ref: 2976d93eb96d322b1428eb83dc5f9f2f0bd58646
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
